In [9]:
import pandas as pd

In [14]:
df = pd.read_csv("../dataset/wind_forecast.csv")

In [15]:
df.head()

         date  time_frame  hrs     u     v    ws      wd  farm
0  2009070100           1    1  2.34 -0.79  2.47  108.68     1
1  2009070100           1    2  2.18 -0.99  2.40  114.31     1
2  2009070100           1    3  2.20 -1.21  2.51  118.71     1
3  2009070100           1    4  2.35 -1.40  2.73  120.86     1
4  2009070100           1    5  2.53 -1.47  2.93  120.13     1

In [12]:
del df['date']

In [6]:
df.to_csv("../dataset/wind_forecast_edited.csv", index=False)

In [7]:
df = pd.read_csv("../dataset/wind_forecast_edited.csv")

In [8]:
df.head()

         date  hrs     u     v    ws      wd  farm  time_frame
0  2009070100    1  2.34 -0.79  2.47  108.68     1           1
1  2009070100    2  2.18 -0.99  2.40  114.31     1           2
2  2009070100    3  2.20 -1.21  2.51  118.71     1           3
3  2009070100    4  2.35 -1.40  2.73  120.86     1           4
4  2009070100    5  2.53 -1.47  2.93  120.13     1           5